# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 78) do

  create_table "admin_faculties", :force => true do |t|
  end

  create_table "answerdoubts", :force => true do |t|
    t.column "answer",   :text
    t.column "doubt_id", :integer
  end

  create_table "answers", :force => true do |t|
    t.column "answer",      :text
    t.column "question_id", :integer
    t.column "user_id",     :integer
    t.column "fac_id",      :integer
  end

  create_table "articles", :force => true do |t|
    t.column "faculty_id",   :integer
    t.column "title",        :string
    t.column "synopsis",     :text
    t.column "body",         :text
    t.column "published",    :boolean,  :default => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "published_at", :datetime
    t.column "category_id",  :integer
    t.column "tags",         :text
  end

  create_table "articles_categories", :force => true do |t|
    t.column "articles_category", :string
  end

  create_table "branches", :force => true do |t|
    t.column "branch",    :string
    t.column "course_id", :integer
  end

  create_table "categories", :force => true do |t|
    t.column "category", :string
  end

  create_table "cities", :force => true do |t|
    t.column "city",     :string
    t.column "state_id", :integer
  end

  create_table "clubs", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "category",    :string
    t.column "type",        :string
    t.column "do",          :string
    t.column "dont",        :string
    t.column "do1",         :string
    t.column "do2",         :string
    t.column "dont1",       :string
    t.column "dont2",       :string
    t.column "caption",     :text
    t.column "picture_id",  :integer
    t.column "user_id",     :integer
  end

  create_table "colleges", :force => true do |t|
    t.column "college", :string
    t.column "city_id", :integer
  end

  create_table "companies", :force => true do |t|
    t.column "c_name", :string, :limit => 128, :default => "", :null => false
  end

  create_table "contents", :force => true do |t|
    t.column "category", :string
  end

  create_table "courses", :force => true do |t|
    t.column "course",     :string
    t.column "college_id", :integer
  end

  create_table "create_papers", :force => true do |t|
  end

  create_table "doubts", :force => true do |t|
    t.column "doubt",       :text
    t.column "answer",      :text
    t.column "question_id", :integer
    t.column "user_id",     :integer
    t.column "fac_id",      :integer
  end

  create_table "exams", :force => true do |t|
    t.column "question",     :string
    t.column "option_a",     :string
    t.column "option_b",     :string
    t.column "option_c",     :string
    t.column "option_d",     :string
    t.column "answer",       :string
    t.column "published",    :boolean,  :default => false
    t.column "created_at",   :datetime
    t.column "published_at", :datetime
    t.column "option_e",     :string
    t.column "picture_id",   :integer
    t.column "instructions", :string
  end

  create_table "exams_papers", :id => false, :force => true do |t|
    t.column "exam_id",  :integer
    t.column "paper_id", :integer
  end

  create_table "faculties", :force => true do |t|
    t.column "email",                     :string,   :limit => 128, :default => "",    :null => false
    t.column "hashed_password",           :string,   :limit => 64
    t.column "fac_displayname",           :string,   :limit => 64,  :default => "",    :null => false
    t.column "fac_title",                 :string,   :limit => 64,  :default => "",    :null => false
    t.column "fac_department",            :string,   :limit => 64,  :default => "",    :null => false
    t.column "fac_edudetails",            :string,   :limit => 128, :default => "",    :null => false
    t.column "fac_aboutme",               :string,   :limit => 128, :default => "",    :null => false
    t.column "gender",                    :string
    t.column "dob",                       :string
    t.column "enabled",                   :boolean,                 :default => true,  :null => false
    t.column "notify_file",               :boolean,                 :default => true
    t.column "notify_link",               :boolean,                 :default => false
    t.column "notify_article",            :boolean,                 :default => true
    t.column "privacy_friend",            :integer,                 :default => 1
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "default_target",            :string,   :limit => 20
    t.column "default_filter",            :string,   :limit => 20
    t.column "notify_request",            :boolean,                 :default => true
    t.column "notify_private",            :boolean,                 :default => true
    t.column "notify_notice",             :boolean,                 :default => true
    t.column "notify_plain",              :boolean,                 :default => false
    t.column "notify_reply",              :boolean,                 :default => true
    t.column "privacy_email",             :integer,                 :default => 2
    t.column "privacy_profile",           :integer,                 :default => 2
    t.column "privacy_location",          :integer,                 :default => 2
    t.column "privacy_country",           :integer,                 :default => 2
    t.column "privacy_age",               :integer,                 :default => 2
    t.column "privacy_gender",            :integer,                 :default => 2
    t.column "privacy_sn",                :integer,                 :default => 2
    t.column "privacy_im",                :integer,                 :default => 2
    t.column "privacy_web",               :integer,                 :default => 2
    t.column "height",                    :integer
    t.column "width",                     :integer
    t.column "content_type",              :string
    t.column "size",                      :integer
    t.column "filename",                  :string
    t.column "admincollege_id",           :integer
    t.column "admin_flag",                :integer
    t.column "profiles_sanction",         :integer
    t.column "profiles_used",             :integer
    t.column "state_id",                  :integer
    t.column "city_id",                   :integer
    t.column "college_id",                :integer
  end

  create_table "faculty_admins", :force => true do |t|
  end

  create_table "forums", :force => true do |t|
    t.column "subject",    :string
    t.column "message",    :string
    t.column "clubid",     :integer
    t.column "clubname",   :string
    t.column "created_at", :datetime
    t.column "picture_id", :integer
  end

  create_table "friendships", :force => true do |t|
    t.column "faculty_id",  :string,   :default => "", :null => false
    t.column "friend_id",   :string,   :default => "", :null => false
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
  end

  create_table "group_memberships", :force => true do |t|
    t.column "user_id",  :integer,  :null => false
    t.column "group_id", :integer,  :null => false
    t.column "added_at", :datetime
  end

  create_table "groups", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "owner_id",   :integer
    t.column "created_at", :datetime
  end

  create_table "im_memberships", :force => true do |t|
    t.column "faculty_id", :integer,  :null => false
    t.column "im_id",      :integer,  :null => false
    t.column "created_at", :datetime
    t.column "username",   :string
  end

  create_table "ims", :force => true do |t|
    t.column "name", :string,               :default => "", :null => false
    t.column "code", :string, :limit => 50
  end

  create_table "mybranches", :id => false, :force => true do |t|
    t.column "faculty_id", :integer
    t.column "branch_id",  :integer
  end

  create_table "note_recipients", :id => false, :force => true do |t|
    t.column "faculty_id", :integer, :null => false
    t.column "note_id",    :integer, :null => false
    t.column "branch_id",  :integer
  end

  create_table "notes", :force => true do |t|
    t.column "type",             :string
    t.column "size",             :integer
    t.column "content_type",     :string
    t.column "filename",         :string
    t.column "is_private",       :boolean,  :default => false
    t.column "is_public",        :boolean,  :default => false
    t.column "sender_id",        :integer,                     :null => false
    t.column "reply_to",         :integer
    t.column "group_id",         :integer
    t.column "private_group_id", :integer
    t.column "created_at",       :datetime
    t.column "note",             :text,     :default => "",    :null => false
    t.column "link",             :string
    t.column "event_title",      :string
    t.column "event_location",   :string
    t.column "event_time",       :datetime
  end

  create_table "papers", :force => true do |t|
    t.column "c_name",       :string
    t.column "c_year",       :integer
    t.column "test_name",    :string
    t.column "exam_type",    :string
    t.column "admin_id",     :integer
    t.column "exam_value",   :string
    t.column "timer",        :time
    t.column "introduction", :text
  end

  create_table "performances", :force => true do |t|
    t.column "user_id",     :integer
    t.column "paper_id",    :integer
    t.column "performance", :string
    t.column "right",       :integer
    t.column "wrong",       :integer
  end

  create_table "pictures", :force => true do |t|
    t.column "comment",      :string
    t.column "name",         :string
    t.column "content_type", :string
    t.column "data",         :binary
  end

  create_table "posts", :force => true do |t|
    t.column "message", :string
    t.column "thought", :string
    t.column "forumid", :integer
  end

  create_table "private_group_memberships", :force => true do |t|
    t.column "faculty_id",       :integer,  :null => false
    t.column "private_group_id", :integer,  :null => false
    t.column "requested_at",     :datetime
    t.column "approved_at",      :datetime
    t.column "invited_at",       :datetime
    t.column "accepted_at",      :datetime
    t.column "created_at",       :datetime
  end

  create_table "private_groups", :force => true do |t|
    t.column "name",        :string,   :default => "", :null => false
    t.column "description", :text
    t.column "owner_id",    :integer
    t.column "created_at",  :datetime
  end

  create_table "questions", :force => true do |t|
    t.column "question", :string
    t.column "user_id",  :integer
    t.column "fac_id",   :integer
  end

  create_table "rates", :force => true do |t|
    t.column "club_id", :integer
    t.column "rate",    :string
    t.column "user_id", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  create_table "searches", :force => true do |t|
    t.column "search", :string
  end

  create_table "simple_captcha_data", :force => true do |t|
    t.column "key",        :string,   :limit => 40
    t.column "value",      :string,   :limit => 6
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "sn_memberships", :force => true do |t|
    t.column "faculty_id",        :integer,  :null => false
    t.column "social_network_id", :integer,  :null => false
    t.column "created_at",        :datetime
    t.column "username",          :string
  end

  create_table "social_networks", :force => true do |t|
    t.column "name", :string,               :default => "", :null => false
    t.column "code", :string, :limit => 50
  end

  create_table "states", :force => true do |t|
    t.column "state", :string
  end

  create_table "users", :force => true do |t|
    t.column "firstname",       :string,   :limit => 64,  :default => "",   :null => false
    t.column "lastname",        :string,   :limit => 64,  :default => "",   :null => false
    t.column "email",           :string,   :limit => 128, :default => "",   :null => false
    t.column "hashed_password", :string,   :limit => 64
    t.column "activate",        :boolean,                 :default => true, :null => false
    t.column "pass_month_year", :date
    t.column "branch",          :string,                  :default => "",   :null => false
    t.column "semester",        :string,                  :default => "",   :null => false
    t.column "state",           :string,                  :default => "",   :null => false
    t.column "city",            :string,                  :default => "",   :null => false
    t.column "college",         :string,                  :default => "",   :null => false
    t.column "course",          :string,                  :default => "",   :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "last_login_at",   :datetime
    t.column "visibility",      :integer
    t.column "status",          :integer
    t.column "verifyflag",      :boolean
    t.column "blockflag",       :boolean
  end

end
